const mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017/art', { useNewUrlParser: true, useUnifiedTopology: true });

const ArtPiece = require('../models/art');

const entries = [
  {
    name: 'JOSE TRUJILLO Oil Painting Impressionism WHITE FLOWER GARDENIA STILL LIFE NR',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/8HUAAOSwJIxddUME/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: '14x12 Original Painting - Diary Series - At Tate Modern',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/MjoAAOSwpKRdeOMY/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'Modernist Cubism Nude Iconic Figure Abstract Oil Painting Signed Hodgson',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/a-IAAOSwcStdeNyD/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'Abstract Indian Woman Canvas Oil Painting Print Picture Home Wall Art Decor',
    price: '259',
    img: 'https://i.ebayimg.com/thumbs/images/g/NVkAAOSwKVJdentE/s-l225.jpg',
    size: 'medium',
    category: 'paintings',
  },
  {
    name: 'US Ture Love Kiss Abstract Art on Canvas Painting Wall Art Picture Prints Decor',
    price: '233',
    img: 'https://i.ebayimg.com/thumbs/images/g/2-0AAOSwxmNdcSA3/s-l225.jpg',
    size: 'medium',
    category: 'paintings',
  },
  {
    name: 'Abstract Indian Woman Canvas Oil Painting Print Picture Home Wall Art Decor',
    price: '266',
    img: 'https://i.ebayimg.com/thumbs/images/g/nhQAAOSwkDhdd5RX/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'Painting Older Spanish Lady Oil Canvas 19th Century',
    price: '278',
    img: 'https://ir.ebaystatic.com/cr/v/c1/s_1x2.gif',
    size: 'large',
    category: 'paintings',
  },
  {
    name: 'GATO GOMEZ PAINTING RETRO VINTAGE HALLOWEEN VAMPIRE DRACULA HAUNTED GHOST',
    price: '1294',
    img: 'https://i.ebayimg.com/thumbs/images/g/X3UAAOSwPNxdVrFP/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'original art painting,Vintage Halloween style , acrylic on wooden board',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/I-YAAOSw5n9depD5/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'Still Life Painting on Canvas',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/9wsAAOSwZL5ddnRO/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'Still Life Painting on Canvas',
    price: '0.99',
    img: 'https://ir.ebaystatic.com/cr/v/c1/s_1x2.gif',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'Face Painting',
    price: '0.99',
    img: 'https://ir.ebaystatic.com/cr/v/c1/s_1x2.gif',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'SALLY KING BENEDICT Face Painting 4 X 6',
    price: '4657',
    img: 'https://ir.ebaystatic.com/cr/v/c1/s_1x2.gif',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'Painting 1943',
    price: '0.99',
    img: 'https://ir.ebaystatic.com/cr/v/c1/s_1x2.gif',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'Obata -Original Wartime Painting 1943 -Winter Dawn, Missouri Valley',
    price: '4 689,75 руб.',
    img: 'https://ir.ebaystatic.com/cr/v/c1/s_1x2.gif',
    size: 'medium',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '1246',
    img: 'https://i.ebayimg.com/thumbs/images/g/3AgAAOSw-9tdWbzL/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '4857',
    img: 'https://i.ebayimg.com/thumbs/images/g/Fl8AAOSwsWddZfsr/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '4857',
    img: 'https://i.ebayimg.com/thumbs/images/g/nUUAAOSw8sZdVE1z/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/5mIAAOSw-D5dekIf/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '30',
    img: 'https://i.ebayimg.com/thumbs/images/g/b1cAAOSwQy9dd7N8/s-l225.jpg',
    size: 'large',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTINGн',
    price: '4789',
    img: 'https://i.ebayimg.com/thumbs/images/g/LoMAAOSw5LZcwuZ1/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '3573',
    img: 'https://i.ebayimg.com/thumbs/images/g/gCoAAOSwEflcwuHK/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '1378',
    img: 'https://i.ebayimg.com/thumbs/images/g/i-AAAOSwkZxdOLU6/s-l225.jpg',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '4234',
    img: 'https://i.ebayimg.com/thumbs/images/g/2ikAAOSwruVa9JwY/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/-xwAAOSwo2xdepnO/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '789',
    img: 'https://i.ebayimg.com/thumbs/images/g/FcQAAOSw6OtdVqxI/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/oIgAAOSw0IpddUTA/s-l225.jpg',
    size: 'medium',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/tCAAAOSwFyVdeVUf/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '3456',
    img: 'https://i.ebayimg.com/thumbs/images/g/xRAAAOSwECtcpmKD/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/hNIAAOSw3ExdeN0p/s-l225.jpg',
    size: 'medium',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/~~sAAOSwhvtdeN8p/s-l225.jpg',
    size: 'medium',
    category: 'paintings',
  },
  {
    name: 'AMERICAN ARTIST ANITA PHILYAW FINE ORIGINAL PAINTING',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/1g0AAOSwhbZdem4v/s-l225.jpg',
    size: 'small',
    category: 'paintings',
  },
  {
    name: 'Handmade composition bronze caucasian girl',
    price: '2345',
    img: 'https://i.ebayimg.com/thumbs/images/g/FfAAAOSw0rddep3M/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag"',
    price: '3124',
    img: 'https://i.ebayimg.com/thumbs/images/g/56EAAOSwMspdep3H/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag"',
    price: '1234',
    img: 'https://i.ebayimg.com/thumbs/images/g/OxIAAOSwMXddep3U/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag"',
    price: '2345',
    img: 'https://i.ebayimg.com/thumbs/images/g/WKIAAOSwJ6JdemTQ/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag',
    price: '4342',
    img: 'https://i.ebayimg.com/thumbs/images/g/ilQAAOSwyX9dep51/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag"',
    price: '1345',
    img: 'https://i.ebayimg.com/thumbs/images/g/L2IAAOSwUYtdelUt/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag"',
    price: '2352',
    img: 'https://i.ebayimg.com/thumbs/images/g/AVEAAOSw4Btdep27/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag"',
    price: '17709',
    img: 'https://i.ebayimg.com/thumbs/images/g/yP4AAOSwElJdep5u/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag"',
    price: '4591',
    img: 'https://i.ebayimg.com/thumbs/images/g/ipEAAOSwkABdep3A/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag"',
    price: '1049',
    img: 'https://i.ebayimg.com/thumbs/images/g/SYIAAOSwmN9dep23/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag"',
    price: '1311',
    img: 'https://i.ebayimg.com/thumbs/images/g/PakAAOSwYL1delUm/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag',
    price: '7213',
    img: 'https://i.ebayimg.com/thumbs/images/g/vacAAOSwgq5demSs/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag"',
    price: '2295',
    img: 'https://i.ebayimg.com/thumbs/images/g/tkUAAOSwSYtdelZm/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition "Bars on a snag"',
    price: '2623',
    img: 'https://i.ebayimg.com/thumbs/images/g/HKsAAOSwKjRdep3P/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1967',
    img: 'https://i.ebayimg.com/thumbs/images/g/0C0AAOSwltNdemTR/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1770',
    img: 'https://i.ebayimg.com/thumbs/images/g/1K0AAOSwrYJdelE~/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1242',
    img: 'https://i.ebayimg.com/thumbs/images/g/5lcAAOSwCgJdemS0/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '7215',
    img: 'https://i.ebayimg.com/thumbs/images/g/bicAAOSwpuFdemM5/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1967',
    img: 'https://i.ebayimg.com/thumbs/images/g/9uEAAOSwachdelOf/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1835',
    img: 'https://i.ebayimg.com/thumbs/images/g/~kkAAOSwzKhdelLc/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '2098',
    img: 'https://i.ebayimg.com/thumbs/images/g/ooIAAOSw2M5demTF/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '2361',
    img: 'https://i.ebayimg.com/thumbs/images/g/Ju4AAOSw9kRdelim/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '2098',
    img: 'https://i.ebayimg.com/thumbs/images/g/msgAAOSwlf9delDc/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '2098',
    img: 'https://i.ebayimg.com/thumbs/images/g/7HIAAOSwQVddelL~/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '2098',
    img: 'https://i.ebayimg.com/thumbs/images/g/71IAAOSwOEVdelMP/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '2164',
    img: 'https://i.ebayimg.com/thumbs/images/g/Ix0AAOSwNGJdelL2/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '2295',
    img: 'https://i.ebayimg.com/thumbs/images/g/p~oAAOSwq9hdelZs/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1902',
    img: 'https://i.ebayimg.com/thumbs/images/g/DQ8AAOSwweFdemM0/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1709',
    img: 'https://i.ebayimg.com/thumbs/images/g/TAoAAOSw3updemSy/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '2097',
    img: 'https://i.ebayimg.com/thumbs/images/g/C-gAAOSwa4xdelPy/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1443',
    img: 'https://i.ebayimg.com/thumbs/images/g/32QAAOSw85ldemTM/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1049',
    img: 'https://i.ebayimg.com/thumbs/images/g/vaoAAOSwtLhdelil/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1705',
    img: 'https://i.ebayimg.com/thumbs/images/g/xooAAOSwVShdelUk/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '2426',
    img: 'https://i.ebayimg.com/thumbs/images/g/oscAAOSw18pdemMo/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '918',
    img: 'https://i.ebayimg.com/thumbs/images/g/Z-oAAOSwBgFdelZf/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1639',
    img: 'https://i.ebayimg.com/thumbs/images/g/vZAAAOSwVAxdelUp/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1836',
    img: 'https://i.ebayimg.com/thumbs/images/g/B6EAAOSwmRVdelix/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '655',
    img: 'https://i.ebayimg.com/thumbs/images/g/iKQAAOSwDpBdelNG/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1574',
    img: 'https://i.ebayimg.com/thumbs/images/g/Z9wAAOSw409delU8/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1902',
    img: 'https://i.ebayimg.com/thumbs/images/g/TFgAAOSwwyZdemMj/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '1705',
    img: 'https://i.ebayimg.com/thumbs/images/g/59gAAOSwzQRdemMq/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade Composition',
    price: '19021',
    img: 'https://i.ebayimg.com/thumbs/images/g/UfAAAOSwbmpdemMw/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade composition bronze warrior soldier',
    price: '20989',
    img: 'https://i.ebayimg.com/thumbs/images/g/FokAAOSwnb5demSv/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade composition bronze warrior soldier',
    price: '1180',
    img: 'https://i.ebayimg.com/thumbs/images/g/ZHYAAOSwrNhdelih/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade composition bronze warrior soldier',
    price: '1246',
    img: 'https://i.ebayimg.com/thumbs/images/g/2YgAAOSw85ldel2T/s-l225.jpg',
    size: 'medium',
    category: 'sculptures',
  },
  {
    name: 'Handmade composition bronze warrior soldier',
    price: '66',
    img: 'https://i.ebayimg.com/thumbs/images/g/iCAAAOSwX9ldeeeD/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'LOUIS WAIN SIGNED CAT WATERCOLOUR POSTCARD',
    price: '66',
    img: 'https://i.ebayimg.com/thumbs/images/g/GZcAAOSwQmRdeefE/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'LOUIS WAIN SIGNED CAT WATERCOLOUR POSTCARD',
    price: '66',
    img: 'https://i.ebayimg.com/thumbs/images/g/x1AAAOSw799deehb/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Handmade composition bronze warrior soldier',
    price: '4525',
    img: 'https://i.ebayimg.com/thumbs/images/g/EDsAAOSwUUhctK1W/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'LOUIS WAIN SIGNED CAT WATERCOLOUR POSTCARD',
    price: '81',
    img: 'https://i.ebayimg.com/thumbs/images/g/af0AAOSwkRtdeouq/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'LOUIS WAIN SIGNED CAT WATERCOLOUR POSTCARD',
    price: '0.99',
    img: 'https://i.ebayimg.com/thumbs/images/g/NggAAOSweXNdeo~9/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'LOUIS WAIN SIGNED CAT WATERCOLOUR POSTCARD',
    price: '1508',
    img: 'https://i.ebayimg.com/thumbs/images/g/fHEAAOSwgPNdeoIv/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Gay Nude Akt Drawing Zeichnung auf 425 g Papier Original 20x30 cm',
    price: '1902',
    img: 'https://i.ebayimg.com/thumbs/images/g/SR0AAOSwcStdcg1N/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Gay Nude Akt Drawing Zeichnung auf 425 g Papier Original 20x30 cm',
    price: '3534',
    img: 'https://i.ebayimg.com/thumbs/images/g/oNYAAOSwLyRdehGe/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'LOUIS WAIN SIGNED CAT WATERCOLOUR POSTCARD - THE NOTE DULY REACHED.',
    price: '5667',
    img: 'https://i.ebayimg.com/thumbs/images/g/vtcAAOSwRl9dekeg/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Kohlezeichnung, ua. nach Dürer, monogr. AK 1975',
    price: '2558',
    img: 'https://i.ebayimg.com/thumbs/images/g/qjIAAOSwsrFdegfo/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Kohlezeichnung, ua. nach Dürer, monogr. AK 1975',
    price: '4525',
    img: 'https://i.ebayimg.com/thumbs/images/g/3VEAAOSwNtVdenDe/s-l225.jpg',
    size: 'medium',
    category: 'drawings',
  },
  {
    name: 'Kohlezeichnung, ua. nach Dürer, monogr. AK 1975',
    price: '4525',
    img: 'https://i.ebayimg.com/thumbs/images/g/js8AAOSw8FFdenEp/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Andreas Noßmann Original - "Die vom Ross gefallenen Kastanien" (DS 05.09.2019)',
    price: '4409',
    img: 'https://i.ebayimg.com/thumbs/images/g/eAsAAOSwhJJdepH4/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Andreas Noßmann Original',
    price: '809',
    img: 'https://i.ebayimg.com/thumbs/images/g/Mu0AAOSwL1xdelVY/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Новое объявлениеПабло Пикассо рисунок подписан на оригинальной бумаге 60-х годов',
    price: '4525',
    img: 'https://i.ebayimg.com/thumbs/images/g/KzEAAOSwZ3Bden9V/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Kohlezeichnung, ua. nach Dürer, monogr. AK 1975',
    price: '809',
    img: 'https://i.ebayimg.com/thumbs/images/g/BP8AAOSwoIFdOHT-/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Kohlezeichnung, ua. nach Dürer, monogr. AK 1975',
    price: '7805',
    img: 'https://i.ebayimg.com/thumbs/images/g/UiIAAOSwESRb~bA3/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Kohlezeichnung, ua. nach Dürer, monogr. AK 1975',
    price: '819',
    img: 'https://i.ebayimg.com/thumbs/images/g/DyIAAOSwMQ1cEC3a/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'LÜTHI ORIGINAL COLLAGE FOTO STÄNDCHEN HERBERT RICKMANN KASSEL',
    price: '72',
    img: 'https://i.ebayimg.com/thumbs/images/g/U4AAAOSwVlRdehnE/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Zeichnung, Personen am Wassertrog, 19.Jh.',
    price: '720',
    img: 'https://i.ebayimg.com/thumbs/images/g/yR0AAOSwcB1deoVH/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Kohlezeichnung, ua. nach Dürer, monogr. AK 1975',
    price: '720',
    img: 'https://i.ebayimg.com/thumbs/images/g/0OEAAOSwfctdeo7g/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Konvolut Zeichnungen, akademische Studien, Akte, 1940er Jahre',
    price: '720',
    img: 'https://i.ebayimg.com/thumbs/images/g/XAUAAOSwP-pdeo04/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'KIRCHNER MISCHTECHNIK UNIKAT 1991 FÜR HERBERT RICKMANN VP: 1800,-€*',
    price: '72',
    img: 'https://i.ebayimg.com/thumbs/images/g/JGoAAOSwINRdejfj/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
  {
    name: 'Paris, Notre Dame, Sacré Coeur sign.',
    price: '720',
    img: 'https://i.ebayimg.com/thumbs/images/g/9B4AAOSwezRdeoOe/s-l225.jpg',
    size: 'small',
    category: 'drawings',
  },
];

ArtPiece.insertMany(entries).then(() => {
  mongoose.connection.close();
});
